export const quizSetData = {
  REC: [201, 202, 203, 206, 209, 208],
  0: [44, 45, 46, 1, 2, 3],
  1: [47, 48, 49, 4, 5, 6],
  2: [50, 51, 52, 7, 8, 9],
  3: [53, 54, 55, 10, 11, 12],
  4: [56, 57, 58, 13, 14, 15],
  5: [59, 60, 61, 16, 17, 18],
  6: [62, 63, 64, 19, 20, 21],
  7: [65, 66, 67, 22, 23, 24],
  8: [68, 57, 28, 25, 26, 27],
};

export const quizData = [
  {
    id: 201,
    desc: '听听是谁在说话',
    options: [
      '蛮三刀',
      '德邦',
      '琴女',
      '德玛',
    ],
    answerIndex: 2,
    hasImage: true,
  },
  {
    id: 202,
    desc: '这首歌是以下哪位歌手的作品',
    options: [
      '周杰伦',
      '杨坤',
      '杨幂',
      '周杰',
    ],
    answerIndex: 0,
    hasImage: false,
  },
  {
    id: 203,
    desc: '还记得第一次光速QA的欣喜么?该BGM是瑞雯哪个皮肤的登场音乐',
    options: [
      '兔女郎',
      '冠军之刃',
      '替父从军',
      '电玩勇者',
    ],
    answerIndex: 3,
    hasImage: true,
  },
  {
    id: 204,
    desc: '请选出与上面播放的音乐最符合的英雄角色',
    options: [
      '安妮',
      '皎月',
      '光辉',
      '阿木木',
    ],
    answerIndex: 3,
    hasImage: true,
  },
  {
    id: 205,
    desc: '请判断上面播放音乐的音乐风格',
    options: [
      '摇滚',
      '电音',
      '嘻哈',
      '古典',
    ],
    answerIndex: 0,
    hasImage: false,
  },
  {
    id: 206,
    desc: '请选出这首由PGONE演唱歌曲的作品名',
    options: [
      'first blood',
      'triple kill',
      'Penta kill',
      'shut down',
    ],
    answerIndex: 2,
    hasImage: false,
  },
  {
    id: 207,
    desc: 'Summoner\'s Call作为排位BGM，是由以下哪个合唱团演唱',
    options: [
      '彩虹合唱团',
      '彩红合唱团',
      '色彩合唱团',
      '彩绿合唱团',
    ],
    answerIndex: 0,
    hasImage: false,
  },
  {
    id: 208,
    desc: '该歌曲是下面哪次大赛的主题曲',
    options: [
      'S3',
      'S4',
      'LPL5',
      'S7',
    ],
    answerIndex: 1,
    hasImage: false,
  },
  {
    id: 209,
    desc: '该歌曲为2015年MSI演唱的LPL出征曲，其由谁演唱',
    options: [
      'Rookie & Cool',
      'Cool & Uzi',
      'Rookie & Gogoing',
      'PDD & white五五开',
    ],
    answerIndex: 0,
    hasImage: false,
  },
  {
    id: 210,
    desc: '这首燃爆的BGM属于下面哪位英雄',
    options: [
      '瑞兹',
      '老鼠',
      '加里奥',
      'Uzi',
    ],
    answerIndex: 3,
    hasImage: true,
  },
  {
    hasImage: false,
    answerIndex: 3,
    options: [
      '坚持不放弃我们就是赢家',
      '秒退的我也想骂',
      '5秒钟收你人头',
      '希望大家喜欢这首歌',
    ],
    id: 44,
    desc: '作者奶兔翻唱这首《the lol》的希望是？',
  },
  {
    hasImage: false,
    answerIndex: 3,
    options: [
      'yeah',
      '~yeah ~oh',
      'Let me song',
      '会长想打人',
    ],
    id: 45,
    desc: '作者忧忧喵录这首《英雄联盟》录呕血了,为什么？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '去逛街鸟',
      '洒下激动热泪',
      '心跳加速',
      '隐忍的嘶吼',
    ],
    id: 46,
    desc: '作者少年霜翻唱完这首《lol英雄联盟》做了什么事？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '广大撸友',
      '广大基友',
      '广大朋友',
      '广大后宫',
    ],
    id: 47,
    desc: '作者seven唱的这首《英雄联盟颂》献给谁？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '萧敬腾',
      '雷神托尔',
      '风神一目连',
      '电神比卡丘',
    ],
    id: 48,
    desc: '这首《爱的大未来》是谁唱的？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      'PG ONE',
      '毁灭博士',
      '比伯',
      '吴亦凡',
    ],
    id: 49,
    desc: '这次音乐节的哪位嘉宾唱过这首《英雄归来》？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      'Allan ',
      'Alan Walker',
      '艾伦小天使',
      'Allan Taylor',
    ],
    id: 50,
    desc: '这首《ALL FALLS DOWN》是音乐节的哪位嘉宾创作的？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      '探险家伊泽瑞尔',
      'Alan Walker',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 51,
    desc: '这首《Sing Me to Sleep》是音乐节的哪位嘉宾创作的？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      'Alan Walker',
      '卫宫士郎',
      'Saber',
      '远坂凛',
    ],
    id: 52,
    desc: '这首《Faded》是音乐节的哪位嘉宾创作的？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '李云迪',
      '王力宏',
      '胡歌',
      '霍建华',
    ],
    id: 53,
    desc: '这次音乐节的哪位嘉宾弹过《肖邦传奇》？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      '郎朗',
      '李云迪',
      '霍尊',
      '宋茜',
    ],
    id: 54,
    desc: '这次音乐节的哪位嘉宾弹过《彩云追月》？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '拳头公司',
      '小拳拳锤你胸口',
      '鹅不食草',
      '吃鸡',
    ],
    id: 55,
    desc: '这首《bit rush》是英雄联盟的发明者创作的,这个公司俗称',
  },
  {
    hasImage: false,
    answerIndex: 3,
    options: [
      '请开始你的表演',
      '皮皮虾我们走',
      '小哥哥',
      '这个选项是正确答案',
    ],
    id: 56,
    desc: '听到这首《Welcome to Planet Urf 》,你最想说什么话？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '初音未来',
      '洛天依',
      '赫兹',
      '人工智障',
    ],
    id: 57,
    desc: '这首歌是“LiveMusic二次元音乐视听新干线”的其中一站主要角色演唱的,她是谁？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '渡边麻友',
      '柏木由纪',
      '指原莉乃',
      '前田敦子',
    ],
    id: 58,
    desc: '这首歌是“LiveMusic二次元音乐视听新干线”的其中一站主要角色演唱的,她是谁？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      'PDD',
      'MISS',
      '小智',
      'white',
    ],
    id: 59,
    desc: '这次英雄联盟音乐节的合作主播翻唱过这首《滴答》,她是谁？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '上海彩虹室内合唱团',
      '北京彩虹室内合唱团',
      '深圳彩虹室内合唱团',
      '香港彩虹室内合唱团',
    ],
    id: 60,
    desc: '这首《感觉身体被掏空》是音乐节的哪位嘉宾唱的？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '尚雯婕',
      '奇迹觉醒',
      '迪丽热巴',
      '李湘',
    ],
    id: 61,
    desc: '这首歌是“LiveMusic二次元音乐视听新干线”的其中一站主要角色演唱的,她是谁？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      '我是传奇',
      'Legends Never Die',
      '正义者联盟',
      '复仇者联盟',
    ],
    id: 62,
    desc: '这首歌是2017年英雄联盟的主题曲,请问名称是？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      'Ignite',
      '熵',
      '决策树',
      '信息增益',
    ],
    id: 63,
    desc: '这首歌是2016年英雄联盟的主题曲,请问名称是？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      'Worlds Collide',
      '飞龙在天',
      '亢龙有悔',
      '神龙摆尾',
    ],
    id: 64,
    desc: '这首歌是2015年英雄联盟的主题曲,请问名称是？',
  },
  {
    hasImage: false,
    answerIndex: 1,
    options: [
      '猩球崛起',
      'Warriors',
      '星球大战',
      '星际穿越',
    ],
    id: 65,
    desc: '这首歌是2014年英雄联盟的主题曲,请问名称是？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      "Summoner's Call",
      '今晚吃鸡',
      '我要抱抱',
      '绝地求生',
    ],
    id: 66,
    desc: '这首歌据说是拳头最经典的原创音乐,请问名称是？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      '徐梦圆',
      '双笙',
      '徐娇',
      '张大仙',
    ],
    id: 67,
    desc: '这首《color-X 3D》是音乐节的哪位嘉宾的代表作？',
  },
  {
    hasImage: false,
    answerIndex: 0,
    options: [
      'sky',
      '李晓峰',
      'Syc',
      ' Guangmo',
    ],
    id: 68,
    desc: '由Alan Walker创作的这首歌的曲名是？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '山隐之焰奥恩',
      '德玛西亚之翼',
      '冰霜女巫',
      '唤潮鲛姬',
    ],
    id: 1,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '源计划联合艾希',
      '冰霜女巫',
      '诺克萨斯之手德莱厄斯',
      '大元素使拉克丝',
    ],
    id: 2,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '山隐之焰奥恩',
      '诺克萨斯之手德莱厄斯',
      '源计划联合艾希',
      '冰霜女巫',
    ],
    id: 3,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '山隐之焰奥恩',
      '符文法师瑞兹',
      '源计划联合艾希',
      '冰霜女巫',
    ],
    id: 4,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '山隐之焰奥恩',
      '符文法师瑞兹',
      '铸星龙王奥瑞利安索尔',
      '九尾妖狐阿狸',
    ],
    id: 5,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '诺克萨斯之手德莱厄斯',
      '符文法师瑞兹',
      '铸星龙王奥瑞利安索尔',
      '源计划林易',
    ],
    id: 6,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '海兽祭司俄洛伊',
      '源计划联合艾希',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 7,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '探险家伊泽瑞尔',
      '符文法师瑞兹',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 8,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '源计划林易',
      '唤潮鲛姬娜美',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 9,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '德玛西亚之翼奎因',
      '符文法师瑞兹',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 10,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '德玛西亚之翼奎因',
      '皮城执法官蔚',
      '冰霜女巫',
      '山隐之焰奥恩',
    ],
    id: 11,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '九尾妖狐阿狸',
      '德玛西亚之翼',
      '冰霜女巫',
      '唤潮鲛姬',
    ],
    id: 12,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '符文法师瑞兹',
      '弗雷尔卓德之心布隆',
      '冰霜女巫',
      '唤潮鲛姬',
    ],
    id: 13,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '符文法师瑞兹',
      '冰霜女巫',
      '唤潮鲛姬',
      '大元素使拉克丝',
    ],
    id: 14,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '星之守护者厄运小姐',
      '冰霜女巫',
      '唤潮鲛姬',
      '大元素使拉克丝',
    ],
    id: 15,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '星之守护者厄运小姐',
      '赏金猎人厄运小姐',
      '铸星龙王奥瑞利安索尔',
      '九尾妖狐阿狸',
    ],
    id: 16,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '大元素使拉克丝',
      '灵魂守卫乌迪尔',
      '铸星龙王奥瑞利安索尔',
      '九尾妖狐阿狸',
    ],
    id: 17,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '大元素使拉克丝',
      '神龙烈焰金克丝',
      '唤潮鲛姬',
      '九尾妖狐阿狸',
    ],
    id: 18,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '丧尸杀手金克丝',
      '神龙烈焰金克丝',
      '唤潮鲛姬',
      '九尾妖狐阿狸',
    ],
    id: 19,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '丧尸杀手金克丝',
      '霸天零式赛恩',
      '唤潮鲛姬',
      '冰霜女巫',
    ],
    id: 20,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '圣锤之毅波比',
      '霸天零式赛恩',
      '唤潮鲛姬',
      '神龙烈焰金克丝',
    ],
    id: 21,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '圣锤之毅波比',
      '圣枪游侠卢锡安',
      '九尾妖狐阿狸',
      '神龙烈焰金克丝',
    ],
    id: 22,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '电玩勇者锐雯',
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '神龙烈焰金克丝',
    ],
    id: 23,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '电玩勇者锐雯',
      '银河魔装机神兰博',
      '霸天零式赛恩',
      '唤潮鲛姬',
    ],
    id: 24,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '电玩勇者锐雯',
      '沙漠皇帝阿兹尔',
      '丧尸杀手金克丝',
      '九尾妖狐阿狸',
    ],
    id: 25,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '未来战士凯特琳',
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '电玩勇者锐雯',
    ],
    id: 26,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      'DJ娑娜',
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '神龙烈焰金克丝',
    ],
    id: 27,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      'DJ娑娜',
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '岩雀塔莉垭',
    ],
    id: 28,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '霸天零式赛恩',
      '圣枪游侠卢锡安',
      '九尾妖狐阿狸',
      '暴走萝莉金克丝',
    ],
    id: 29,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '殇之木乃伊阿木木',
      '神龙烈焰金克丝',
      '唤潮鲛姬',
      '九尾妖狐阿狸',
    ],
    id: 30,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '岩雀塔莉垭',
      '海洋之灾普朗克',
      '唤潮鲛姬',
      '九尾妖狐阿狸',
    ],
    id: 31,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '岩雀塔莉垭',
      '冰霜女巫丽桑卓',
      '九尾妖狐阿狸',
      'DJ娑娜',
    ],
    id: 32,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '大元素使拉克丝',
      '神龙烈焰金克丝',
      '唤潮鲛姬',
      '牧魂人约里克',
    ],
    id: 33,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '大元素使拉克丝',
      '美猴王孙悟空',
      '唤潮鲛姬',
      '牧魂人约里克',
    ],
    id: 34,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '大元素使拉克丝',
      '美猴王孙悟空',
      '戏命师烬',
      '牧魂人约里克',
    ],
    id: 35,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '大元素使拉克丝',
      '美猴王孙悟空',
      '戏命师烬',
      '驯龙炮手崔丝塔娜',
    ],
    id: 36,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '荣耀行刑官德莱文',
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '神龙烈焰金克丝',
    ],
    id: 37,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '圣枪游侠卢锡安',
      '霸天零式赛恩',
      '亡灵战神赛恩',
      '美猴王孙悟空',
    ],
    id: 38,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 1,
    options: [
      '圣枪游侠卢锡安',
      '永猎双子千珏',
      '亡灵战神赛恩',
      '大元素使拉克丝',
    ],
    id: 39,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '邪恶小法师维迦',
      '霸天零式赛恩',
      '唤潮鲛姬',
      '神龙烈焰金克丝',
    ],
    id: 40,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 3,
    options: [
      '电玩勇者锐雯',
      '沙漠皇帝阿兹尔',
      '丧尸杀手金克丝',
      '死兆星锤石',
    ],
    id: 41,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 2,
    options: [
      '冰霜女巫',
      '唤潮鲛姬',
      '皎月女神黛安娜',
      '大元素使拉克丝',
    ],
    id: 42,
    desc: '猜猜这是谁的歌？',
  },
  {
    hasImage: true,
    answerIndex: 0,
    options: [
      '时间刺客艾克',
      '德玛西亚之翼奎因',
      '符文法师瑞兹',
      '冰霜女巫',
    ],
    id: 43,
    desc: '猜猜这是谁的歌？',
  },
];

